StoreApp.Web/Components/CategoriesListViewComponent.cs
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Data.Abstract;
using StoreApp.Web.Models;

namespace StoreApp.Web.Components;

public class CategoriesListViewComponent:ViewComponent
{
    private IStoreRepository _storeRepository;

    public CategoriesListViewComponent(IStoreRepository storeRepository)
    {
        _storeRepository = storeRepository;
    }

    public IViewComponentResult Invoke()
    {
        ViewBag.SelectedCategory = RouteData?.Values["category"];

        return View(_storeRepository
                                    .Categories
                                    .Select(c => new CategoryViewModel{
                                                                        Id = c.Id,
                                                                        Name = c.Name,
                                                                        Url = c.Url
                                                                      }  
                                           )
                                    .ToList()
                    );   
         
    }


    
}

StoreApp.Web/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StoreApp.Data.Abstract;
using StoreApp.Web.Models;

namespace StoreApp.Web.Controllers;

public class HomeController:Controller
{
    public int pageSize = 3; //Sayfa başına kaç ürün gelsin?
    private readonly IStoreRepository _storeRepository;

    private readonly IMapper _mapper;

    public HomeController(IStoreRepository storeRepository, IMapper mapper)
    {
        _storeRepository = storeRepository;
        _mapper = mapper;
    }


    //locahost:7000/?page=1
    public ActionResult Index(string category, int page =1)              // public ActionResult Index() => View(_storeRepository.Products); şeklinde de tanımlanabilir eğer parantez istenmiyorsa
    {


        return View(new ProductListViewModel{
            Products = _storeRepository
                                    .GetProductsByCategory(category, page, pageSize)
                                    .Select(product => _mapper.Map<ProductViewModel>(product)),
            PageInfo = new PageInfo{
                ItemsPerPage = pageSize,
                CurrentPage = page,
                TotalItems = _storeRepository.GetProductCount(category)
            }   
        });

    }










}

StoreApp.Web/Views/Home/Index.cshtml
@model ProductListViewModel



<div class="row">
    <div class="col-md-3">
        <vc:categories-list />
    </div>

    <div class="col-md-9">

                    @if(Model.Products.Count()==0)
                    {
                        <p>Ürün Bulunamadı.</p>
                    }

                    @foreach(var p in Model.Products)
                    {
                        <div class="card card-outline-secondary mb-2 p-2">
                            <div class="d-flex justify-content-between">
                                    <div>
                                        <h4>@p.Name</h4>
                                        <p>@p.Description</p>
                                    </div>

                                    <div>
                                        <span class="badge rounded-pill text-bg-success">@p.Price TL</span>
                                    </div>
                            </div>

                            <form asp-page ="/Cart" method="post">
                                <input type="hidden" asp-for = "@p.Id" name="Id">
                                <button type="submit" class="btn btn-outline-success btn-sm pull-right" style="float:right">Sepete Ekle</button>
                            </form> 
                        </div>

                    }


                    @if(Model.PageInfo.TotalPages>1)
                    {
                        <div 
                            page-model = "@Model.PageInfo" 
                            page-action = "Index" 
                            page-class = "btn"
                            page-class-link = "btn-outline-dark"
                            page-class-active="btn-dark"
                            class="btn-group my-2"
                        ></div>
                    }

    </div>
</div>